#!/bin/bash
# Setup script for local development
# Run this with: source setup_env.sh

# Detect Vulkan SDK location
if [ -n "$VULKAN_SDK" ]; then
    echo "Using existing VULKAN_SDK: $VULKAN_SDK"
else
    # Try common installation locations
    VULKAN_SDK_LOCATIONS=(
        "/opt/vulkansdk/*/x86_64"
        "/usr/local/share/vulkan"
        "/usr"
    )
    
    for location in "${VULKAN_SDK_LOCATIONS[@]}"; do
        FOUND=$(find $location -name "shaderc.hpp" 2>/dev/null | head -1)
        if [ -n "$FOUND" ]; then
            VULKAN_SDK=$(dirname $(dirname $FOUND))
            echo "Found Vulkan SDK at: $VULKAN_SDK"
            break
        fi
    done
    
    if [ -z "$VULKAN_SDK" ]; then
        echo "ERROR: Vulkan SDK not found!"
        echo "Please install Vulkan SDK from https://vulkan.lunarg.com/"
        return 1
    fi
fi

# Export environment variables
export VULKAN_SDK
export CPLUS_INCLUDE_PATH="$VULKAN_SDK/include:$CPLUS_INCLUDE_PATH"
export LIBRARY_PATH="$VULKAN_SDK/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$VULKAN_SDK/lib:$LD_LIBRARY_PATH"
export PATH="$VULKAN_SDK/bin:$PATH"

# Generate .bazelrc.user with dynamic paths
cat > .bazelrc.user << EOF
# User-specific Bazel configuration
# This file is auto-generated by setup_env.sh and should NOT be committed to git

# Vulkan SDK paths
build --linkopt=-L$VULKAN_SDK/lib
build --linkopt=-Wl,-rpath,$VULKAN_SDK/lib
EOF

echo "Environment configured successfully!"
echo "VULKAN_SDK=$VULKAN_SDK"
echo "Generated .bazelrc.user with Vulkan SDK library paths"
echo "You can now run: bazelisk build //..."
